services:
  app:
    build: .
    container_name: songelite-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/usr/src/app
    command: ["npx", "nodemon", "app.js"]

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: songelite-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=songelite
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    restart: always

  redis:
    image: redis:latest
    container_name: songelite-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
